what_to_learn = [
    'D3 - https://d3js.org/',
    'Newline - https://www.newline.co/',
    'D3 - https://bl.ocks.org/',
    'D3 In Depth - https://www.d3indepth.com/force-layout/',
    'Framer Motion - https://www.framer.com/motion/',
    'Angular - https://angular.io/',
    'Free Intro to Python - https://www.codecademy.com/learn/learn-python',
    'Django - https://www.djangoproject.com/',
    'Python - https://www.python.org/',
    'Typescript - https://www.typescriptlang.org/',
    'Gatsby - https://www.gatsbyjs.com/',
    'NextJS - https://nextjs.org/',
    'React Native - https://reactnative.dev/',
    'Auth for Ruby on Rails - https://tuts.alexmercedcoder.com/ruby-tut/',
    'DevNursery - https://main.devnursery.com/',
    'Dark Mode - https://dev.to/ditarahma08/dark-mode-with-css-variable-1p57',
    '9 Projects for Front End - https://dev.to/simonholdorf/9-projects-you-can-do-to-become-a-frontend-master-in-2020-n2h',
    'Tips For Being a Great Programmer - https://dev.to/emmabostian/101-tips-for-being-a-great-programmer-human-36nl',
    'Interview Study Guide - https://dev.to/seattledataguy/the-interview-study-guide-for-software-engineers-764',
    '70 JS Interview Questions - https://dev.to/macmacky/70-javascript-interview-questions-5gfi',
    'CSS Variables - https://css-tricks.com/difference-between-types-of-css-variables/'
]
